name: Test build and push on heroku with maven

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        # Email that you use with heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        # The appname to use for deploying/updating
        heroku_app_name: ${{secrets.HEROKU_APP_DEV}}


          - name: Build
            run: mvn --batch-mode -DskipTests package

          - name: Test
            run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

          - name: Report
            uses: dorny/test-reporter@v1
            if: always()
            with:
              name: Maven Tests
              path: target/surefire-reports/*.xml
              reporter: java-junit
              fail-on-error: true
